export const securityOptions = {
  none: { label: '不加密（仅限可信网络）', value: 'none' },
  tls: { label: '使用加密证书', value: 'tls' },
  reality: { label: 'Reality 免证书加密', value: 'reality' },
}

export const transportOptions = [
  { label: '协议默认方式', value: '' },
  { label: 'WebSocket', value: 'ws' },
  { label: 'gRPC', value: 'grpc' },
]

export const protocols = [
  {
    value: 'vless',
    label: 'VLESS',
    summary: '常用连接协议，可使用证书或 Reality 保护连接',
    network: 'tcp',
    security: ['none', 'tls', 'reality'],
    transports: true,
    credential: 'uuid-flow',
    recommended: true,
    common: true,
    stable: true,
    defaultPort: 443,
  },
  {
    value: 'trojan',
    label: 'Trojan',
    summary: '使用密码连接，建议同时配置加密证书',
    network: 'tcp',
    security: ['tls', 'none'],
    transports: true,
    credential: 'password',
    common: true,
    stable: true,
    defaultPort: 443,
  },
  {
    value: 'hysteria2',
    label: 'Hysteria2',
    summary: '适合延迟较高或网络不稳定的场景，必须配置证书',
    network: 'udp',
    security: ['tls'],
    transports: false,
    credential: 'password',
    common: true,
    stable: true,
    defaultPort: 443,
  },
  {
    value: 'tuic',
    label: 'TUIC',
    summary: '适合移动网络，使用双重身份信息连接',
    network: 'udp',
    security: ['tls'],
    transports: false,
    credential: 'uuid-password',
    common: true,
    defaultPort: 443,
  },
  {
    value: 'shadowsocks',
    label: 'Shadowsocks',
    summary: '自带加密，可按需要使用 TCP 或 UDP',
    network: 'tcp',
    networks: ['tcp', 'udp'],
    security: ['none'],
    transports: false,
    credential: 'shadowsocks',
    common: true,
    stable: true,
    defaultPort: 8388,
  },
  {
    value: 'vmess',
    label: 'VMess',
    summary: '用于兼容旧客户端，新建服务建议优先选择 VLESS',
    network: 'tcp',
    security: ['none', 'tls'],
    transports: true,
    credential: 'uuid-alter',
    stable: true,
    defaultPort: 443,
  },
  {
    value: 'anytls',
    label: 'AnyTLS',
    summary: '使用密码和加密证书建立连接',
    network: 'tcp',
    security: ['tls'],
    transports: false,
    credential: 'password',
  },
  {
    value: 'socks',
    label: 'SOCKS5',
    summary: '适合可信内网，不应直接开放到公网',
    network: 'tcp',
    security: ['none'],
    transports: false,
    credential: 'user-password',
    common: true,
    stable: true,
    defaultPort: 1080,
  },
  {
    value: 'http',
    label: 'HTTP',
    summary: '供支持 HTTP 代理的客户端使用，可设置用户名和密码',
    network: 'tcp',
    security: ['none', 'tls'],
    transports: false,
    credential: 'user-password',
    stable: true,
    defaultPort: 8080,
  },
  {
    value: 'naive',
    label: 'NaiveProxy',
    summary: '使用用户名、密码和加密证书连接',
    network: 'tcp',
    security: ['tls'],
    transports: false,
    credential: 'user-password',
  },
  {
    value: 'hysteria',
    label: 'Hysteria',
    summary: '用于兼容旧版 Hysteria 客户端',
    network: 'udp',
    security: ['tls'],
    transports: false,
    credential: 'password',
  },
  {
    value: 'shadowtls',
    label: 'ShadowTLS',
    summary: '使用密码连接，适用于兼容 ShadowTLS 的客户端',
    network: 'tcp',
    security: ['none'],
    transports: false,
    credential: 'password',
    listenerExtras: 'shadowtls',
  },
  {
    value: 'snell',
    label: 'Snell',
    summary: '适用于 Surge 客户端，使用共享密钥连接',
    network: 'tcp',
    security: ['none'],
    transports: false,
    credential: 'psk',
    listenerExtras: 'snell',
  },
]

export const protocolMap = Object.fromEntries(protocols.map((protocol) => [protocol.value, protocol]))

export const shadowsocksMethods = [
  '2022-blake3-aes-128-gcm',
  '2022-blake3-aes-256-gcm',
  '2022-blake3-chacha20-poly1305',
  'aes-128-gcm',
  'aes-256-gcm',
  'chacha20-ietf-poly1305',
]

export function createListenerModel(existing, nodeID = '') {
  const spec = existing?.spec || {}
  const security = spec.reality?.enabled ? 'reality' : spec.tls?.enabled ? 'tls' : protocolMap[spec.protocol]?.security?.[0] || 'none'
  return {
    id: existing?.id || '',
    node_id: existing?.node_id || nodeID,
    name: existing?.name || '',
    listen_address: existing?.listen_address || '0.0.0.0',
    port: existing?.port || 443,
    backend_port: existing?.backend_port || 0,
    enabled: existing?.enabled ?? true,
    outbound_id: existing?.outbound_id || '',
    protocol: spec.protocol || 'vless',
    network: spec.network || 'tcp',
    security,
    tls_server_name: spec.tls?.server_name || '',
    certificate_id: spec.tls?.certificate_id || '',
    tls_alpn: spec.tls?.alpn || [],
    tls_min_version: spec.tls?.min_version || '',
    tls_max_version: spec.tls?.max_version || '',
    reality_handshake_server: spec.reality?.handshake_server || 'www.microsoft.com',
    reality_handshake_port: spec.reality?.handshake_port || 443,
    reality_short_ids: spec.reality?.short_ids || [],
    reality_key_id: spec.reality?.key_id || '',
    transport_type: spec.transport?.type || '',
    transport_path: spec.transport?.path || '',
    transport_host: spec.transport?.host || '',
    transport_service_name: spec.transport?.service_name || '',
    hysteria_up_mbps: spec.hysteria?.up_mbps || 0,
    hysteria_down_mbps: spec.hysteria?.down_mbps || 0,
    hysteria_obfuscation: spec.hysteria?.obfuscation || '',
    tuic_congestion_control: spec.tuic?.congestion_control || 'bbr',
    snell_version: spec.snell?.version || 5,
    snell_mode: spec.snell?.mode || '',
    shadowtls_version: spec.shadowtls?.version || 3,
    shadowtls_handshake_server: spec.shadowtls?.handshake_server || '',
    shadowtls_handshake_port: spec.shadowtls?.handshake_port || 443,
    shared_port: Boolean(existing && ['127.0.0.1', '::1'].includes(existing.listen_address) && existing.backend_port && existing.backend_port !== existing.port),
    ingress_sni: '',
  }
}

export function listenerPayload(model) {
  const definition = protocolMap[model.protocol]
  const security = definition.security.includes(model.security) ? model.security : definition.security[0]
  return {
    node_id: model.node_id,
    name: model.name,
    listen_address: model.shared_port ? '127.0.0.1' : '0.0.0.0',
    port: Number(model.port),
    backend_port: model.shared_port ? Number(model.backend_port || 0) : 0,
    enabled: Boolean(model.enabled),
    outbound_id: model.outbound_id || '',
    spec: {
      protocol: model.protocol,
      network: definition.networks?.includes(model.network) ? model.network : definition.network,
      tls: {
        enabled: security === 'tls' || security === 'reality',
        server_name: security === 'tls' ? model.tls_server_name : security === 'reality' ? model.reality_handshake_server : '',
        alpn: model.tls_alpn || [],
        min_version: model.tls_min_version || '',
        max_version: model.tls_max_version || '',
        cipher_suites: [],
        certificate_id: security === 'tls' ? model.certificate_id : '',
      },
      reality: {
        enabled: security === 'reality',
        handshake_server: security === 'reality' ? model.reality_handshake_server : '',
        handshake_port: security === 'reality' ? Number(model.reality_handshake_port || 443) : 0,
        short_ids: security === 'reality' ? model.reality_short_ids || [] : [],
        key_id: security === 'reality' ? model.reality_key_id : '',
      },
      transport: {
        type: definition.transports ? model.transport_type || '' : '',
        path: definition.transports ? model.transport_path || '' : '',
        host: definition.transports ? model.transport_host || '' : '',
        service_name: definition.transports ? model.transport_service_name || '' : '',
      },
      hysteria: {
        up_mbps: Number(model.hysteria_up_mbps || 0),
        down_mbps: Number(model.hysteria_down_mbps || 0),
        obfuscation: model.hysteria_obfuscation || '',
      },
      tuic: { congestion_control: model.tuic_congestion_control || '' },
      snell: { version: Number(model.snell_version || 0), mode: model.snell_mode || '' },
      shadowtls: {
        version: Number(model.shadowtls_version || 0),
        handshake_server: model.shadowtls_handshake_server || '',
        handshake_port: Number(model.shadowtls_handshake_port || 0),
      },
    },
  }
}

export function createCredentialModel(protocol) {
  return {
    name: '',
    enabled: true,
    uuid: '',
    password: '',
    username: '',
    method: protocol === 'shadowsocks' ? shadowsocksMethods[0] : '',
    psk: '',
    flow: '',
    alter_id: 0,
  }
}
