package control_test

import (
	"encoding/base64"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/liyuwei007036/polaris/internal/control"
)

func TestNodeRenameAutomaticRealityAndEndpointAliasFlow(t *testing.T) {
	store, err := control.Open(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	secret, err := store.CreateInitialAdmin(t.Context(), "admin@example.com", "correct horse battery staple")
	if err != nil {
		t.Fatal(err)
	}
	server, err := control.NewServer(store, false)
	if err != nil {
		t.Fatal(err)
	}
	httpServer := httptest.NewServer(server.Handler())
	defer httpServer.Close()
	session, csrfToken := login(t, httpServer.URL, secret)
	nodeID := approveTestNode(t, server, httpServer.URL, session, csrfToken, "reality-node")
	otherNodeID := approveTestNode(t, server, httpServer.URL, session, csrfToken, "other-node")

	response := request(t, http.MethodPut, httpServer.URL+"/api/v1/nodes/"+nodeID+"/name", map[string]string{"name": "新加坡主节点"}, session, csrfToken)
	if response.StatusCode != http.StatusOK {
		t.Fatalf("rename node: got %d", response.StatusCode)
	}
	response.Body.Close()
	response = request(t, http.MethodPut, httpServer.URL+"/api/v1/nodes/"+otherNodeID+"/name", map[string]string{"name": "新加坡主节点"}, session, csrfToken)
	if response.StatusCode != http.StatusConflict {
		t.Fatalf("duplicate node name: got %d", response.StatusCode)
	}
	response.Body.Close()
	if err := store.SetNodeClientAddress(t.Context(), nodeID, "sg.example.com"); err != nil {
		t.Fatal(err)
	}

	response = request(t, http.MethodPost, httpServer.URL+"/api/v1/listeners/quick", map[string]any{
		"listener": map[string]any{
			"node_id": nodeID, "name": "自动 Reality", "connection_domain": "listener.example.com", "port": 443, "enabled": true,
			"spec": map[string]any{
				"protocol": "vless", "network": "tcp", "tls": map[string]any{"enabled": true},
				"reality": map[string]any{
					"enabled": true, "key_id": "browser-must-not-control-this", "short_ids": []string{"browser-value"},
					"handshake_server": "www.microsoft.com", "handshake_port": 443,
				},
			},
		},
		"accounts": []map[string]any{{"id": "", "name": "alice", "alias": "新加坡专线 01", "enabled": true, "outbound_id": "direct"}},
	}, session, csrfToken)
	if response.StatusCode != http.StatusCreated {
		t.Fatalf("create automatic Reality listener: got %d", response.StatusCode)
	}
	var created struct {
		Listener  control.Listener   `json:"listener"`
		Endpoints []control.Endpoint `json:"endpoints"`
	}
	decodeBody(t, response, &created)
	if created.Listener.Spec.Reality.KeyID == "" || created.Listener.Spec.Reality.KeyID == "browser-must-not-control-this" {
		t.Fatalf("Reality key was not generated by the server: %#v", created.Listener.Spec.Reality)
	}
	if len(created.Listener.Spec.Reality.ShortIDs) != 1 || created.Listener.Spec.Reality.ShortIDs[0] == "browser-value" {
		t.Fatalf("Reality short ID was not generated by the server: %#v", created.Listener.Spec.Reality.ShortIDs)
	}
	if len(created.Endpoints) != 1 || created.Endpoints[0].Alias != "新加坡专线 01" {
		t.Fatalf("endpoint alias was not stored: %#v", created.Endpoints)
	}
	groupInput := map[string]any{
		"name": "新加坡节点", "strategy": "select",
		"members": []map[string]any{{"kind": "endpoint", "id": created.Endpoints[0].ID}},
	}
	response = request(t, http.MethodPost, httpServer.URL+"/api/v1/mihomo/proxy-groups", groupInput, session, csrfToken)
	if response.StatusCode != http.StatusCreated {
		t.Fatalf("create proxy group through API: got %d", response.StatusCode)
	}
	response.Body.Close()
	response = request(t, http.MethodPost, httpServer.URL+"/api/v1/mihomo/proxy-groups", groupInput, session, csrfToken)
	if response.StatusCode != http.StatusConflict {
		t.Fatalf("duplicate proxy group status = %d", response.StatusCode)
	}
	var groupError map[string]string
	decodeBody(t, response, &groupError)
	if !strings.Contains(groupError["error"], "新加坡节点") || !strings.Contains(groupError["error"], "已存在") {
		t.Fatalf("duplicate proxy group error = %#v", groupError)
	}
	if _, _, err := store.CompileNodeConfig(t.Context(), nodeID); err != nil {
		t.Fatalf("compile automatically generated Reality listener: %v", err)
	}

	_, token, err := store.CreateSubscription(t.Context(), control.SubscriptionInput{
		Kind: control.ClientSubscription, Name: "alias-check", EndpointIDs: []string{created.Endpoints[0].ID}, Enabled: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	encoded, err := store.GenerateClientSubscription(t.Context(), token)
	if err != nil {
		t.Fatal(err)
	}
	decoded, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(decoded), "listener.example.com:443") || !strings.Contains(string(decoded), "sni=www.microsoft.com") || !strings.Contains(string(decoded), "%E6%96%B0%E5%8A%A0%E5%9D%A1%E4%B8%93%E7%BA%BF+01") {
		t.Fatalf("subscription did not keep the connection domain, Reality target and endpoint alias separate: %s", decoded)
	}
	if err := store.DeleteEndpoint(t.Context(), created.Endpoints[0].ID); err != control.ErrConflict {
		t.Fatalf("referenced endpoint deletion = %v, want conflict", err)
	}
	if err := store.DeleteListener(t.Context(), created.Listener.ID); err != control.ErrConflict {
		t.Fatalf("listener with referenced endpoint deletion = %v, want conflict", err)
	}
}
